# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DEARPHOTO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DEARPHOTO
  # Rx
  pod 'RxSwift', '< 6.2.0'
  pod 'RxCocoa', '< 6.2.0'
  pod 'RxGesture', '< 4.1.0'
  pod 'RxDataSources', '<5.1.0'
  
  # Others
  pod 'SwiftKeychainWrapper'
  pod 'Kingfisher', '~> 7.0'
  pod 'DynamicBottomSheet'
  pod 'SnapKit'
  pod 'Then'

end
